export const SET_IN_STORE_CARD_AS_SELECTED = 'SET_IN_STORE_CARD_AS_SELECTED';
export const SET_IN_STORE_CART_CONTENT = 'SET_IN_STORE_CART_CONTENT';
export const SET_IN_STORE_INITIAL_CARDS_LIST = 'SET_IN_STORE_INITIAL_CARDS_LIST';
export const SET_IN_STORE_NEW_CARD_DETAILS = 'SET_IN_STORE_NEW_CARD_DETAILS';
export const SET_IN_STORE_ORDER_DETAILS = 'SET_IN_STORE_ORDER_DETAILS';
export const SET_IN_STORE_PRODUCTS_LIST = 'SET_IN_STORE_PRODUCTS_LIST';
